### ISSUE TITLE
Printing of a Julia struct, unhandled exception inside IPython

### ISSUE THREAD

**Issue by cowfarts** [JuliaPy/pyjulia#116]
Setup: 
* Win7x64
* Anaconda3 4.2.0 x64
* Julia 0.7.0-DEV.1328 x64
* PyCall v1.14.0+ (state of master on 8/13/2017 to include [PyCall.jl #422](https://github.com/JuliaPy/PyCall.jl/pull/422))
* pyjulia (state of master on 8/13/2017 to include #113)

Desired operations: 
* Execute constructor of a Julia struct from within Python/IPython via pyjulia
* Print a Julia struct from within Python/IPython via pyjulia
* Access field of a Julia struct from within Python/IPython via pyjulia
* Assign into field of a Julia struct from within Python/IPython via pyjulia

Current test case:
* Load ColorTypes in IPython session via pyjulia (using ColorTypes only as representative of a package including a struct with some simple fields)
* Execute constructor for ColorTypes.RGB
* Attempt to print the constructed object

Results in the unhandled exception shown below.  Manually removed most of the current Julia 0.7.0 deprecation warnings from the printed output.

If the exception for printing (either the entire struct or an individual field) can be addressed, would also appreciate examples of how to perform access and assignment into a field of a Julia struct from Python without error.

---------------------------------------------------------------------------------------------

```
C:\>ipython
Python 3.5.2 |Anaconda 4.2.0 (64-bit)| (default, Jul  5 2016, 11:41:13) [MSC v.1900 64 bit (AMD64)]
Type "copyright", "credits" or "license" for more information.

IPython 5.1.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import julia

In [2]: j = julia.Julia()

In [3]: j.versioninfo()
Julia Version 0.7.0-DEV.1328
Commit eabd0212ed* (2017-08-11 20:34 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-5650U CPU @ 2.20GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, broadwell)
Environment:

In [4]: j.using('ColorTypes')

In [5]: rgb = j.RGB(0.1,0.2,0.3)

In [6]: whos
Variable   Type      Data/Info
------------------------------
j          Julia     <julia.core.Julia object at 0x0000000004653470>
julia      module    <module 'julia' from 'C:\<...>egg\\julia\\__init__.py'>
rgb        jlwrap    <PyCall.jlwrap RGB{Float64}(0.1,0.2,0.3)>

In [7]: j.whos()
                          Base               Module
                       BinDeps  30040 KB     Module
                    ColorTypes  30172 KB     Module
                        Compat  29874 KB     Module
                         Conda  29894 KB     Module
                          Core               Module
             FixedPointNumbers  30447 KB     Module
                          JSON  29951 KB     Module
                    MacroTools  30345 KB     Module
                          Main               Module
                        PyCall  30221 KB     Module
                           SHA  29899 KB     Module
                     URIParser  29848 KB     Module

In [8]: rgb
Out[8]: fatal: error thrown and no exception handler available.
UndefVarError(var=Symbol("#temp#"))
rec_backtrace at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src\stackwalk.c:86
record_backtrace at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src\task.c:246
jl_throw at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src\task.c:568
jl_undefined_var_error at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src\rtutils.c:129
pyjlwrap_getattr at C:\Users\cowfarts\.julia\v0.7\PyCall\src\pytype.jl:390
unknown function (ip: 000000001B179F54)
jl_call_fptr_internal at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src\julia_internal.h:366 [inlined]
jl_call_method_internal at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src\julia_internal.h:385 [inlined]
jl_apply_generic at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src\gf.c:1940
unknown function (ip: 000000001B1221D3)
unknown function (ip: 000000001B122112)
PyAST_FromNode at C:\Anaconda3\python35.dll (unknown line)
PyCFunction_Call at C:\Anaconda3\python35.dll (unknown line)
PyEval_GetFuncDesc at C:\Anaconda3\python35.dll (unknown line)
PyEval_EvalFrameEx at C:\Anaconda3\python35.dll (unknown line)
PyEval_GetFuncDesc at C:\Anaconda3\python35.dll (unknown line)
PyEval_GetFuncDesc at C:\Anaconda3\python35.dll (unknown line)
PyEval_EvalFrameEx at C:\Anaconda3\python35.dll (unknown line)
PyEval_EvalFrameEx at C:\Anaconda3\python35.dll (unknown line)
PyFunction_SetAnnotations at C:\Anaconda3\python35.dll (unknown line)
PyObject_Call at C:\Anaconda3\python35.dll (unknown line)
PyEval_GetFuncDesc at C:\Anaconda3\python35.dll (unknown line)
PyEval_EvalFrameEx at C:\Anaconda3\python35.dll (unknown line)
PyEval_EvalFrameEx at C:\Anaconda3\python35.dll (unknown line)
PyEval_GetFuncDesc at C:\Anaconda3\python35.dll (unknown line)
PyEval_GetFuncDesc at C:\Anaconda3\python35.dll (unknown line)
PyEval_EvalFrameEx at C:\Anaconda3\python35.dll (unknown line)
PyEval_EvalFrameEx at C:\Anaconda3\python35.dll (unknown line)
PyFunction_SetAnnotations at C:\Anaconda3\python35.dll (unknown line)
PyObject_Call at C:\Anaconda3\python35.dll (unknown line)
PyMethod_New at C:\Anaconda3\python35.dll (unknown line)
PyObject_Call at C:\Anaconda3\python35.dll (unknown line)
PyType_Ready at C:\Anaconda3\python35.dll (unknown line)
PyObject_Call at C:\Anaconda3\python35.dll (unknown line)
PyEval_GetFuncDesc at C:\Anaconda3\python35.dll (unknown line)
PyEval_GetFuncDesc at C:\Anaconda3\python35.dll (unknown line)
PyEval_EvalFrameEx at C:\Anaconda3\python35.dll (unknown line)
PyEval_EvalFrameEx at C:\Anaconda3\python35.dll (unknown line)
PyEval_GetFuncDesc at C:\Anaconda3\python35.dll (unknown line)
PyEval_GetFuncDesc at C:\Anaconda3\python35.dll (unknown line)
PyEval_EvalFrameEx at C:\Anaconda3\python35.dll (unknown line)
PyEval_GetFuncDesc at C:\Anaconda3\python35.dll (unknown line)
PyEval_GetFuncDesc at C:\Anaconda3\python35.dll (unknown line)
PyEval_EvalFrameEx at C:\Anaconda3\python35.dll (unknown line)
PyEval_EvalFrameEx at C:\Anaconda3\python35.dll (unknown line)
PyFunction_SetAnnotations at C:\Anaconda3\python35.dll (unknown line)
PyObject_Call at C:\Anaconda3\python35.dll (unknown line)
PyMethod_New at C:\Anaconda3\python35.dll (unknown line)
PyObject_Call at C:\Anaconda3\python35.dll (unknown line)
PyType_Ready at C:\Anaconda3\python35.dll (unknown line)
PyObject_Call at C:\Anaconda3\python35.dll (unknown line)
PyObject_CallFunctionObjArgs at C:\Anaconda3\python35.dll (unknown line)
PyEval_EvalFrameEx at C:\Anaconda3\python35.dll (unknown line)
PyEval_EvalFrameEx at C:\Anaconda3\python35.dll (unknown line)
PyEval_EvalCode at C:\Anaconda3\python35.dll (unknown line)
PyAST_FromNode at C:\Anaconda3\python35.dll (unknown line)
PyAST_FromNode at C:\Anaconda3\python35.dll (unknown line)
PyCFunction_Call at C:\Anaconda3\python35.dll (unknown line)
PyEval_GetFuncDesc at C:\Anaconda3\python35.dll (unknown line)
PyEval_EvalFrameEx at C:\Anaconda3\python35.dll (unknown line)
PyEval_EvalFrameEx at C:\Anaconda3\python35.dll (unknown line)
PyEval_GetFuncDesc at C:\Anaconda3\python35.dll (unknown line)
PyEval_GetFuncDesc at C:\Anaconda3\python35.dll (unknown line)
PyEval_EvalFrameEx at C:\Anaconda3\python35.dll (unknown line)
PyEval_EvalFrameEx at C:\Anaconda3\python35.dll (unknown line)
PyEval_GetFuncDesc at C:\Anaconda3\python35.dll (unknown line)
PyEval_GetFuncDesc at C:\Anaconda3\python35.dll (unknown line)
PyEval_EvalFrameEx at C:\Anaconda3\python35.dll (unknown line)
PyEval_EvalFrameEx at C:\Anaconda3\python35.dll (unknown line)
PyEval_GetFuncDesc at C:\Anaconda3\python35.dll (unknown line)
PyEval_GetFuncDesc at C:\Anaconda3\python35.dll (unknown line)
PyEval_EvalFrameEx at C:\Anaconda3\python35.dll (unknown line)
PyEval_EvalFrameEx at C:\Anaconda3\python35.dll (unknown line)
PyEval_GetFuncDesc at C:\Anaconda3\python35.dll (unknown line)
PyEval_GetFuncDesc at C:\Anaconda3\python35.dll (unknown line)
PyEval_EvalFrameEx at C:\Anaconda3\python35.dll (unknown line)
PyEval_EvalFrameEx at C:\Anaconda3\python35.dll (unknown line)
PyEval_GetFuncDesc at C:\Anaconda3\python35.dll (unknown line)
PyEval_GetFuncDesc at C:\Anaconda3\python35.dll (unknown line)
PyEval_EvalFrameEx at C:\Anaconda3\python35.dll (unknown line)
PyEval_GetFuncDesc at C:\Anaconda3\python35.dll (unknown line)
PyEval_GetFuncDesc at C:\Anaconda3\python35.dll (unknown line)
PyEval_EvalFrameEx at C:\Anaconda3\python35.dll (unknown line)
PyEval_EvalFrameEx at C:\Anaconda3\python35.dll (unknown line)
PyFunction_SetAnnotations at C:\Anaconda3\python35.dll (unknown line)
PyObject_Call at C:\Anaconda3\python35.dll (unknown line)
PyEval_GetFuncDesc at C:\Anaconda3\python35.dll (unknown line)
PyEval_EvalFrameEx at C:\Anaconda3\python35.dll (unknown line)
PyEval_EvalFrameEx at C:\Anaconda3\python35.dll (unknown line)
PyEval_GetFuncDesc at C:\Anaconda3\python35.dll (unknown line)
PyEval_GetFuncDesc at C:\Anaconda3\python35.dll (unknown line)
PyEval_EvalFrameEx at C:\Anaconda3\python35.dll (unknown line)
PyEval_EvalFrameEx at C:\Anaconda3\python35.dll (unknown line)
PyRun_FileExFlags at C:\Anaconda3\python35.dll (unknown line)
PyRun_FileExFlags at C:\Anaconda3\python35.dll (unknown line)
PyRun_SimpleFileExFlags at C:\Anaconda3\python35.dll (unknown line)
PyRun_AnyFileExFlags at C:\Anaconda3\python35.dll (unknown line)
Py_hashtable_copy at C:\Anaconda3\python35.dll (unknown line)
Py_Main at C:\Anaconda3\python35.dll (unknown line)
unknown function (ip: 000000001CF9125B)
BaseThreadInitThunk at C:\Windows\system32\kernel32.dll (unknown line)
RtlUserThreadStart at C:\Windows\SYSTEM32\ntdll.dll (unknown line)

C:\>julia
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: https://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.7.0-DEV.1328 (2017-08-11 20:34 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit eabd0212ed* (1 day old master)
|__/                   |  x86_64-w64-mingw32

julia> Pkg.status()
6 required packages:
 - ColorTypes                    0.6.0
 - Cubature                      1.2.2
 - DSP                           0.3.2
 - DataFrames                    0.10.1
 - Optim                         0.9.3
 - PyCall                        1.14.0+            master
34 additional packages:
 - AbstractFFTs                  0.2.0
 - BinDeps                       0.7.0
 - BufferedStreams               0.3.3
 - Calculus                      0.2.2
 - CommonSubexpressions          0.0.1
 - Compat                        0.30.0
 - Conda                         0.7.0
 - DataArrays                    0.6.2
 - DataStructures                0.6.1
 - DiffBase                      0.2.0
 - FFTW                          0.0.4
 - FileIO                        0.5.1
 - FixedPointNumbers             0.3.9
 - ForwardDiff                   0.5.0
 - GZip                          0.3.0
 - JSON                          0.13.0
 - LibExpat                      0.3.0
 - Libz                          0.2.4
 - LineSearches                  2.2.1
 - MacroTools                    0.3.7
 - NLSolversBase                 2.1.3
 - NaNMath                       0.2.6
 - Parameters                    0.7.2
 - Polynomials                   0.1.6
 - PositiveFactorizations        0.0.4
 - RealInterface                 0.0.3
 - Reexport                      0.0.3
 - SHA                           0.5.0
 - SortingAlgorithms             0.1.1
 - SpecialFunctions              0.3.1
 - StaticArrays                  0.6.2
 - StatsBase                     0.18.0
 - URIParser                     0.2.0
 - WinRPM                        0.2.5

julia>
```

**Comment by musm** [comment]
Trying this on 0.6 I get
```julia
>>> rgb = j.RGB(0.1,0.2,0.3)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'PyCall.jlwrap' object is not callable```

**Comment by cowfarts** [comment]
@musm Are you using current master for PyCall and pyjulia?

**Comment by musm** [comment]
@cowfarts  No I am using the latest tagged versions

**Comment by cowfarts** [comment]
@musm At present, it seems you will need both masters to have [PyCall.jl #422](https://github.com/JuliaPy/PyCall.jl/pull/422) and [pyjulia #113](https://github.com/JuliaPy/pyjulia/pull/113) to allow the constructor to be callable.

**Comment by cowfarts** [comment]
Ok, the printing problem must be an issue with either executing in IPython (most likely) or using Julia-0.7.0-DEV.  

After performing the suggested increased /STACK operation on the Anaconda3 python.exe binary (using the method shown [here](https://github.com/JuliaPy/pyjulia/blob/master/appveyor.yml#L86)), and using Julia-0.6.0, printing the struct or its fields in a standard Python session executes successfully as shown below:

```C:\>python
Python 3.5.2 |Anaconda 4.2.0 (64-bit)| (default, Jul  5 2016, 11:41:13) [MSC v.1
900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import julia
>>> j = julia.Julia()
>>> j.versioninfo()
Julia Version 0.6.0
Commit 903644385b* (2017-06-19 13:05 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-5650U CPU @ 2.20GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, broadwell)
>>> j.using('ColorTypes')
>>> rgb = j.RGB(0.1,0.2,0.3)
>>> rgb
<PyCall.jlwrap RGB{Float64}(0.1,0.2,0.3)>
>>> rgb.r
0.1
>>> rgb.g
0.2
>>> rgb.b
0.3
```

When I attempted using the ipython.exe in the same Anaconda3 installation to which I also performed the same /STACK modification, and executed in conjunction with Julia 0.6.0, the same `UndefVarError(var=Symbol("#temp#"))` as shown in my first post in this issue occurred.

So constructing and printing of an immutable struct seems to be working fine from a standard python session instead of an IPython session.

With respect to mutable structs, how might one go about assigning to a field of a mutable struct from Python?  

Below is an example of using a package ([Sobol.jl](https://github.com/stevengj/Sobol.jl/blob/v0.2.2/src/Sobol.jl#L13)) that contains an export of a mutable struct (f.k.a. "type").  While the alteration I am making to the field below is nonsensical for this package, the example shows modification of a field from this mutable struct performed successfully in Julia, and unsuccessfully from Python.

```
C:\>python
Python 3.5.2 |Anaconda 4.2.0 (64-bit)| (default, Jul  5 2016, 11:41:13) [MSC v.1
900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import julia
>>> j = julia.Julia()
>>> j.versioninfo()
Julia Version 0.6.0
Commit 903644385b* (2017-06-19 13:05 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-5650U CPU @ 2.20GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, broadwell)
>>> j.using('Sobol')
>>> a = j.SobolSeq(2)
>>> a
<PyCall.jlwrap 2-dimensional Sobol sequence on [0,1]^2>
>>> a.m
array([[         1,          1,          1,          1,          1,
                 1,          1,          1,          1,          1,
                 1,          1,          1,          1,          1,
                 1,          1,          1,          1,          1,
                 1,          1,          1,          1,          1,
                 1,          1,          1,          1,          1,
                 1,          1],
       [         1,          3,          5,         15,         17,
                51,         85,        255,        257,        771,
              1285,       3855,       4369,      13107,      21845,
             65535,      65537,     196611,     327685,     983055,
           1114129,    3342387,    5570645,   16711935,   16843009,
          50529027,   84215045,  252645135,  286331153,  858993459,
        1431655765, 4294967295]], dtype=uint32)
>>> a.b
array([0, 0], dtype=uint32)
>>> a.x
array([0, 0], dtype=uint32)
>>> a.n
0
>>> a.n = 1
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'PyCall.jlwrap' object has no attribute 'n'
>>>exit()

C:\>julia
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: https://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.6.0 (2017-06-19 13:05 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-w64-mingw32

julia> using Sobol

julia> a = SobolSeq(2)
2-dimensional Sobol sequence on [0,1]^2

julia> a.
b m  n  x
julia> a.m
2x32 Array{UInt32,2}:
 0x00000001  0x00000001  0x00000001  .  0x00000001  0x00000001  0x00000001
 0x00000001  0x00000003  0x00000005     0x33333333  0x55555555  0xffffffff

julia> a.b
2-element Array{UInt32,1}:
 0x00000000
 0x00000000

julia> a.x
2-element Array{UInt32,1}:
 0x00000000
 0x00000000

julia> a.n
0x00000000

julia> a.n = 1
1

julia> a.n
0x00000001

julia>
```

**Comment by cowfarts** [comment]
And I guess I really just need to know how one might go about assigning into a field of a `mutable struct` that itself is a bits type...assigning into a field that is an array seems to work fine from Python.

**Comment by Keno** [comment]
Fixed in the referenced PyCall PR.

**Comment by cowfarts** [comment]
Just to round out my attempt to set a scalar value field in a `mutable struct`, I was successful with the following hacky exports added to my local PyCall.jl file, re-precompiling, and subsequently loading into the pyjulia session.

I am sure that there is probably a better way to do this.

```julia
# Added within PyCall.jl and exported
pysetfield!(a, b::String, c::Array{T,0}) where {T <: Number} = setfield!(a, Symbol(b), c[])
pysetfield!(a, b::String, c) = setfield!(a, Symbol(b), c)
```

```
C:\>python
Python 3.5.2 |Anaconda 4.2.0 (64-bit)| (default, Jul  5 2016, 11:41:13) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import julia
>>> j = julia.Julia()
>>> j.versioninfo()
Julia Version 0.7.0-DEV.1328
Commit eabd0212ed* (2017-08-11 20:34 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-5650U CPU @ 2.20GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, broadwell)
Environment:
>>> j.using('Sobol')
>>> a = j.SobolSeq(2)
>>> a
<PyCall.jlwrap 2-dimensional Sobol sequence on [0,1]^2>
>>> a.m
array([[         1,          1,          1,          1,          1,
                 1,          1,          1,          1,          1,
                 1,          1,          1,          1,          1,
                 1,          1,          1,          1,          1,
                 1,          1,          1,          1,          1,
                 1,          1,          1,          1,          1,
                 1,          1],
       [         1,          3,          5,         15,         17,
                51,         85,        255,        257,        771,
              1285,       3855,       4369,      13107,      21845,
             65535,      65537,     196611,     327685,     983055,
           1114129,    3342387,    5570645,   16711935,   16843009,
          50529027,   84215045,  252645135,  286331153,  858993459,
        1431655765, 4294967295]], dtype=uint32)
>>> a.b
array([0, 0], dtype=uint32)
>>> a.x
array([0, 0], dtype=uint32)
>>> a.n
0
>>> j.using('PyCall')
>>> import ctypes
>>> j.pysetfield_b(a,'n',ctypes.c_uint32(1))
1
>>> a.n
1
```
