### ISSUE TITLE
JIT Compiling Functions

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaPy/pyjulia#154]
I'm wondering if anyone has found a way to use pyjulia for JIT compilation of functions. This is my attempt:

```py
jul.eval(jul.parse("(x)->2x"))
```

**Comment by stevengj** [comment]
`jul.Meta.parse`?

**Comment by ChrisRackauckas** [comment]
It doesn't look like `Meta` is available:

```julia
>>> import julia
>>> jul = julia.Julia()

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Julia' object has no attribute 'Meta'
```

In fact, it doesn't seem like anything I don't explicitly export is available. A workaround is probably just to export the Base functions that one needs?

**Comment by ChrisRackauckas** [comment]
Actually, I've switched to Python 3.6 and now the original command (which was run in Python 2.7) seems to run, but hit a different error:

```py
>>> jul.eval(jul.parse("(x)->2x"))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/site-packages/julia/core.py", line 449, in eval
    ans = self._call(src)
  File "/usr/lib/python3.6/site-packages/julia/core.py", line 411, in _call
    ans = self.api.jl_eval_string(src.encode('utf-8'))
AttributeError: 'PyCall.jlwrap' object has no attribute 'encode'
```

**Comment by stevengj** [comment]
`Meta` is a problem due to #144: `jul` only has Base functions, which is a terrible design that needs to be fixed.

I think you can do `jlparse = jul.eval("Meta.parse")`, though?

**Comment by stevengj** [comment]
`jul.eval` doesn't call `Base.eval`.  It is evaluating a string.

You probably need `jleval = jul.eval("eval")`

**Comment by stevengj** [comment]
Even easier might be `jul.include_string("(x)->2x")`

**Comment by stevengj** [comment]
Or just `jul.eval("x -> 2x")`, for that matter.
