### ISSUE TITLE
Creating symbols from Python

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaPy/pyjulia#156]
Is this possible? I would like a user to be able to pass a symbol from Python to a Julia API. Do I instead need to implement a conversion from a string for comparisons? That sounds dangerous.

**Comment by ChrisRackauckas** [comment]
```py
>>> jul.Symbol("x")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Julia' object has no attribute 'Symbol'
>>> jul.symbol("x")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Julia' object has no attribute 'symbol'
```

**Comment by stevengj** [comment]
In Julia, you would currently have to do `PyCall.pyjlwrap_new(:x)` to create a Python wrapper for a Julia `Symbol`.   So maybe `jul.eval("PyCall.pyjlwrap_new(:x)")`?

**Comment by iffanh** [comment]
> In Julia, you would currently have to do `PyCall.pyjlwrap_new(:x)` to create a Python wrapper for a Julia `Symbol`. So maybe `jul.eval("PyCall.pyjlwrap_new(:x)")`?
> 
> (I'm guessing slightly here because I don't use pyjulia myself, so I'm working off of how I remember it working and how PyCall works in Julia.)

I know this is an old thread but this works for me, thanks!
