### ISSUE TITLE
PermissionError: [Errno 13] Permission denied when running python-jl

### ISSUE THREAD

**Issue by Seanny123** [JuliaPy/pyjulia#226]
Trying to get around the module import error discussed in #185 using Ubuntu on the Windows Linux Subsytem. However, when I run `python-jl` I'm getting the error:

```
Traceback (most recent call last):
  File "/home/mr_bo/.local/bin/python-jl", line 11, in <module>
    sys.exit(main())
  File "/home/mr_bo/.local/lib/python3.6/site-packages/julia/python_jl.py", line 117, in main
    os.execvp(julia, [julia, "-e", script_jl, "--"] + unused_args)
  File "/usr/lib/python3.6/os.py", line 559, in execvp
    _execvpe(file, args)
  File "/usr/lib/python3.6/os.py", line 603, in _execvpe
    raise saved_exc.with_traceback(saved_tb)
  File "/usr/lib/python3.6/os.py", line 594, in _execvpe
    exec_func(fullname, *argrest)
PermissionError: [Errno 13] Permission denied
```

I'm really unclear about what's causing this. When I do `ls -ls ~/src/julia-1.0.2/bin/julia` I get `48 -rwxr-xr-x 1 mr_bo mr_bo 47296 Nov  8 16:16 /home/mr_bo/src/julia-1.0.2/bin/julia` which leads me to believe everything should be fine? Should I change the user and the group to something else?

**Comment by tkf** [comment]
Hmmm...  Do you have `julia` in the `PATH`?  What happens when you do `python-jl --julia ~/src/julia-1.0.2/bin/julia`?

**Comment by tkf** [comment]
Did it work when you added `julia` to `PATH`? We've never tested it in WSL so that's a good news if so.

> Would it be sensible to add this to the "Troubleshooting" section of the README?

I think it's already mentioned in Installation section.  Generally I think it's better to have a better error message including some instructions.  Sometimes you can't (e.g., when Python segfaults) but here we can catch the exception.

**Comment by Seanny123** [comment]
Sounds good. I'll make a PR today.
