### ISSUE TITLE
julia.core.JuliaError: Exception 'LoadError: LoadError: InitError: UndefVarError: python not defined

### ISSUE THREAD

**Issue by dnk8n** [JuliaPy/pyjulia#228]
**Code:**
```
from julia import Main
demux = Main.using("NextGenSeqUtils.deMux")
```

**Error:**
```
Traceback (most recent call last):
  File "/home/dean/src/work/PacBio_processing_pipeline/singularity/test_julia.py", line 2, in <module>
    demux = Main.using("NextGenSeqUtils.deMux")
  File "/home/dean/.local/share/virtualenvs/PacBio_processing_pipeline-MGndRJCW/lib/python3.7/site-packages/julia/core.py", line 790, in using
    self.eval("using %s" % module)
  File "/home/dean/.local/share/virtualenvs/PacBio_processing_pipeline-MGndRJCW/lib/python3.7/site-packages/julia/core.py", line 769, in eval
    ans = self._call(src)
  File "/home/dean/.local/share/virtualenvs/PacBio_processing_pipeline-MGndRJCW/lib/python3.7/site-packages/julia/core.py", line 702, in _call
    self.check_exception(src)
  File "/home/dean/.local/share/virtualenvs/PacBio_processing_pipeline-MGndRJCW/lib/python3.7/site-packages/julia/core.py", line 752, in check_exception
    .format(exception, src))
julia.core.JuliaError: Exception 'LoadError: LoadError: InitError: UndefVarError: python not defined
during initialization of module PyPlot
while loading /home/dean/.julia/v0.6/NextGenSeqUtils/src/include_all.jl, in expression starting on line 12
while loading /home/dean/.julia/v0.6/NextGenSeqUtils/src/NextGenSeqUtils.jl, in expression starting on line 2' occurred while calling julia code:
using NextGenSeqUtils.deMux
```

To install NextGenSeqUtils, in Julia shell:
if Pyplot is not installed before:
```
ENV["PYTHON"]=""
```
else:
```
ENV["PYTHON"]="/path/to/python/used/with/pyplot"
```

and then:
```
Pkg.update(); Pkg.clone("https://github.com/MurrellGroup/NextGenSeqUtils.jl"); using NextGenSeqUtils
```

**Comment by dnk8n** [comment]
Forgot to add, this package only works for Julia 0.6.4 and earlier.

**Comment by tkf** [comment]
Does it work in pure Julia?

**Comment by dnk8n** [comment]
Yes, the package is working on my system, no problem (Julia 0.6.4).

**Comment by tkf** [comment]
Some guesses/suggestions:

1. Make sure you are using the latest PyCall
2. Configure PyCall to use the python executable used to generate the virtualenv `/home/dean/.local/share/virtualenvs/PacBio_processing_pipeline-MGndRJCW`.  If it is `/usr/bin/python3`, then (but this is supposed to be the default if you are using Linux):

    ```
    ENV["PYTHON"] = "/usr/bin/python3"
    Pkg.build("PyCall")
    ```

3. Try to minimize the example.  Do you really need NextGenSeqUtils.jl to invoke this error?  What happens if you do `/home/dean/.local/share/virtualenvs/PacBio_processing_pipeline-MGndRJCW/bin/python -c "from julia import PyPlot"`?

**Comment by dnk8n** [comment]
From a recent install using pyjulia 0.2.0 and Jupyter Notebook

```
In [1]: from julia import PyPlot
```
```
In [2]: PyPlot
Out[2]: <module 'julia.PyPlot' (<julia.core.JuliaModuleLoader object at 0x7f87a2714ba8>)>
```
```
In [3]: example = PyCall.PyDict()
          example
Out[3]: {}
```
```
In [4]: type(example)
Out[4]: dict
```

So it seems to be working with Pycall. However with NextGenSeqUtils, it only seems to find some of the methods.

```
In [1]: from julia import NextGenSeqUtils
```
```
In [2]: NextGenSeqUtils
Out[2]: <module 'julia.NextGenSeqUtils' (<julia.core.JuliaModuleLoader object at 0x7f87c8735c18>)>
```
```
In [3]: example2 = NextGenSeqUtils.levenshtein
          example2
Out[3]: <PyCall.jlwrap Levenshtein.levenshtein>
```
```
In [4]: example2("AA", "AB")
Out[4]: 1
```

Maybe the issue that the libraries own methods are not callable is something to do with the library re-exporting Levenshtein, [see source here](https://github.com/MurrellGroup/NextGenSeqUtils.jl/blob/a880299500ba0319046aee6ef838b1e66c187378/src/include_all.jl)

```
In [1]: from julia import NextGenSeqUtils
```
```
In [2]: NextGenSeqUtils
Out[2]: <module 'julia.NextGenSeqUtils' (<julia.core.JuliaModuleLoader object at 0x7fbfa3e9dba8>)>
```
```
In [3]: example3 = NextGenSeqUtils.deMux
Out[3]: 
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-4-61ce9f612f47> in <module>
----> 1 example3 = NextGenSeqUtils.deMux
      2 example3

/opt/conda/lib/python3.7/site-packages/julia/core.py in __getattr__(self, name)
    105     def __getattr__(self, name):
    106         try:
--> 107             return self.__try_getattr(name)
    108         except AttributeError:
    109             if name.endswith("_b"):

/opt/conda/lib/python3.7/site-packages/julia/core.py in __try_getattr(self, name)
    130             return self._julia.eval(jl_fullname)
    131 
--> 132         raise AttributeError(name)
    133 
    134 

AttributeError: deMux
```
