### ISSUE TITLE
Conflict with scipy.optimize

### ISSUE THREAD

**Issue by yhtang** [JuliaPy/pyjulia#240]
The following code won't run:
```
import scipy.optimize
import julia
julia.Julia()
```
unless the first line is commented out.

The error message is:
```
Traceback (most recent call last):
  File "/home/.../debug.py", line 4, in <module>
    julia.Julia()
  File "/usr/local/lib/python3.6/site-packages/julia-0.2.1.dev0-py3.6.egg/julia/core.py", line 821, in __init__
    self.__julia = Julia(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/julia-0.2.1.dev0-py3.6.egg/julia/core.py", line 674, in __init__
    self._call(u"using PyCall")
  File "/usr/local/lib/python3.6/site-packages/julia-0.2.1.dev0-py3.6.egg/julia/core.py", line 725, in _call
    ans = self.api.jl_eval_string(src.encode('utf-8'))
TypeError: expected bytes, type found
```

OS/software version:
Fedora 28 `Linux 4.20.11-100.fc28.x86_64 #1 SMP Wed Feb 20 15:51:24 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
Scipy `1.2.1`
julia `0.6.3`
pyjulia `0.2.1.dev0`

**Comment by tkf** [comment]
Thanks for minimizing the example.  Unfortunately, I couldn't reproduce the error.  Also, I can't think of the scenario for this to occur.  Can you do the post-mortem debugging and print what you have in the variable `src`?  If you use IPython, the easiest way to do it is to execute the code that produces the traceback and run `%debug` command.  You can then do `p src`.  If you don't use IPython, you can also do `python -m pdb script.py`; see: https://docs.python.org/3/library/pdb.html

Also, can you workaround the problem with

```python
import julia
julia.Julia()
import scipy.optimize
```

?
