### ISSUE TITLE
FileNotFoundError: [WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by darrencl** [JuliaPy/pyjulia#267]
Hi,

I installed `pyjulia` through `pip` to use a julia package/lib . Below is the list of version.

* `pyjulia`: 0.2.0
* `python`: 3.7.3

The command I used to install.

    pip install julia

During call on `from julia import Main` I got the error below as below

```
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-177-003b030e817a> in <module>
----> 1 from julia import Main

c:\users\tdlukas\appdata\local\programs\python\python37-32\lib\importlib\_bootstrap.py in _find_and_load(name, import_)

c:\users\tdlukas\appdata\local\programs\python\python37-32\lib\importlib\_bootstrap.py in _find_and_load_unlocked(name, import_)

c:\users\tdlukas\appdata\local\programs\python\python37-32\lib\importlib\_bootstrap.py in _load_unlocked(spec)

c:\users\tdlukas\appdata\local\programs\python\python37-32\lib\importlib\_bootstrap.py in _load_backward_compatible(spec)

c:\users\tdlukas\appdata\local\programs\python\python37-32\lib\site-packages\julia\core.py in load_module(self, fullname)
    178         if juliapath == 'Main':
    179             return sys.modules.setdefault(fullname,
--> 180                                           JuliaMainModule(self, fullname))
    181         elif isafunction(self.julia, juliapath):
    182             return self.julia.eval(juliapath)

c:\users\tdlukas\appdata\local\programs\python\python37-32\lib\site-packages\julia\core.py in __init__(self, loader, *args, **kwargs)
     83     def __init__(self, loader, *args, **kwargs):
     84         super(JuliaModule, self).__init__(*args, **kwargs)
---> 85         self._julia = loader.julia
     86         self.__loader__ = loader
     87 

c:\users\tdlukas\appdata\local\programs\python\python37-32\lib\site-packages\julia\core.py in julia(self)
    170     @property
    171     def julia(self):
--> 172         self.__class__.julia = julia = Julia()
    173         return julia
    174 

c:\users\tdlukas\appdata\local\programs\python\python37-32\lib\site-packages\julia\core.py in __init__(self, init_julia, jl_init_path, runtime, jl_runtime_path, debug)
    513 
    514         if init_julia:
--> 515             jlinfo = juliainfo(runtime)
    516             JULIA_HOME, libjulia_path, image_file, depsjlexe = jlinfo[:4]
    517             self._debug("pyprogramname =", depsjlexe)

c:\users\tdlukas\appdata\local\programs\python\python37-32\lib\site-packages\julia\core.py in juliainfo(runtime, **popen_kwargs)
    307         stderr=subprocess.PIPE,
    308         universal_newlines=True,
--> 309         **popen_kwargs)
    310 
    311     stdout, stderr = proc.communicate()

c:\users\tdlukas\appdata\local\programs\python\python37-32\lib\subprocess.py in __init__(self, args, bufsize, executable, stdin, stdout, stderr, preexec_fn, close_fds, shell, cwd, env, universal_newlines, startupinfo, creationflags, restore_signals, start_new_session, pass_fds, encoding, errors, text)
    773                                 c2pread, c2pwrite,
    774                                 errread, errwrite,
--> 775                                 restore_signals, start_new_session)
    776         except:
    777             # Cleanup if the child failed starting.

c:\users\tdlukas\appdata\local\programs\python\python37-32\lib\subprocess.py in _execute_child(self, args, executable, preexec_fn, close_fds, pass_fds, cwd, env, startupinfo, creationflags, shell, p2cread, p2cwrite, c2pread, c2pwrite, errread, errwrite, unused_restore_signals, unused_start_new_session)
   1176                                          env,
   1177                                          os.fspath(cwd) if cwd is not None else None,
-> 1178                                          startupinfo)
   1179             finally:
   1180                 # Child is launched. Close the parent's copy of those pipe

FileNotFoundError: [WinError 2] The system cannot find the file specified
```

Any help would be greatly appreciated!

**Comment by tkf** [comment]
Did you download and install Julia? https://julialang.org/downloads/

You also need to install PyCall. Please see:
https://github.com/JuliaPy/pyjulia#quick-usage
https://pyjulia.readthedocs.io/en/latest/installation.html

**Comment by darrencl** [comment]
Just done all of that and still got error saying not a valid Win32 application. 

* `julia`: 1.1.0
* `PyCall`: 2.3.2

Below is the trace.

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "C:\Users\tdlukas\AppData\Roaming\Python\Python37\site-packages\julia\core.py", line 180, in load_module
    JuliaMainModule(self, fullname))
  File "C:\Users\tdlukas\AppData\Roaming\Python\Python37\site-packages\julia\core.py", line 85, in __init__
    self._julia = loader.julia
  File "C:\Users\tdlukas\AppData\Roaming\Python\Python37\site-packages\julia\core.py", line 172, in julia
    self.__class__.julia = julia = Julia()
  File "C:\Users\tdlukas\AppData\Roaming\Python\Python37\site-packages\julia\core.py", line 529, in __init__
    self.api = ctypes.PyDLL(libjulia_path, ctypes.RTLD_GLOBAL)
  File "C:\Users\tdlukas\AppData\Local\Programs\Python\Python37-32\lib\ctypes\__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 193] %1 is not a valid Win32 application
```

**Comment by darrencl** [comment]
note that I reinstall `pyjulia` at the end to ensure the current ordering.

**Comment by tkf** [comment]
Actually, it is better to run `from julia import Julia; Julia(debug=True)` than `from julia import Main` to get more information.

> not a valid Win32 application

Are you using 32 bit Python and Julia?

**Comment by tkf** [comment]
Before using PyJulia, it is required for PyCall to function properly.  The goal is to make

```julia
julia> using PyCall

julia> PyCall.pyprogramname
"PATH/TO/PYTHON/EXECUTABLE"
```

i.e., `PyCall.pyprogramname` is evaluated to Python executable you want to use.

First, run this in your Python REPL:

```python
>>> import sys
>>> sys.executable
'PATH/TO/PYTHON/EXECUTABLE'
```

copy whatever `sys.executable` is and then use it as `ENV["PYTHON"]` in Julia REPL:

```julia
julia> using Pkg

julia> ENV["PYTHON"] = "PATH/TO/PYTHON/EXECUTABLE"

julia> Pkg.build("PyCall")
```

Now _reboot_ Julia REPL and then try evaluating `PyCall.pyprogramname`.

See also: https://github.com/JuliaPy/PyCall.jl#specifying-the-python-version

**Comment by darrencl** [comment]
Nope, I always use 64-bit, but not sure why it is Win32. Anyway, I just checked and apparently `PyCall.pyprogramname` returns under`/conda/..`, which I am sure it installed automatically during installation as I did not use `python` with conda.

Tried this

```
julia> using Pkg

julia> ENV["PYTHON"] = "C:\\Users\\tdlukas\\AppData\\Local\\Programs\\Python\\Python37-32\\python.exe"
"C:\\Users\\tdlukas\\AppData\\Local\\Programs\\Python\\Python37-32\\python.exe"

julia> Pkg.build("PyCall")
  Building Conda ─→ `C:\Users\tdlukas\.julia\packages\Conda\CpuvI\deps\build.log`
  Building PyCall → `C:\Users\tdlukas\.julia\packages\PyCall\a5Jd3\deps\build.log`

julia> PyCall.libpython
"C:\\Users\\tdlukas\\.julia\\conda\\3\\python36.dll"

julia> PyCall.conda
true
```
But it still seems using conda python. Is there any workaround in this?

**Comment by darrencl** [comment]
Note that I have reload the `julia` (opening new session) and it still could not be changed.

**Comment by tkf** [comment]
Maybe the file `C:\Users\tdlukas\.julia\packages\PyCall\a5Jd3\deps\build.log` has something useful information. Alternatively, try `Pkg.build("PyCall", verbose=true)`.

**Comment by darrencl** [comment]
Just figured out the issue with the logging. Apparently I installed 32-bit python by accident and the julia I installed is 64-bit. 😒
Thanks for the assistance anyway!
