### ISSUE TITLE
Error in Windows when already running in Julia process

### ISSUE THREAD

**Issue by JackDunnNZ** [JuliaPy/pyjulia#287]
[This line](https://github.com/JuliaPy/pyjulia/blob/a90aa32945f9210ab620f47e280ac4f5f8aee29b/src/julia/core.py#L780) gives an error on Windows. Apparently `PyDLL(None)` does not work on Windows:

```
>>> import ctypes
>>> ctypes.PyDLL(None)
 
Traceback (most recent call last):
  File "<pyshell#1>", line 1, in <module>
    ctypes.PyDLL(None)
  File "C:\Users\user\AppData\Local\Programs\Python\Python27\lib\ctypes\__init__.py", line 366, in __init__
    self._handle = _dlopen(self._name, mode)
TypeError: expected string or Unicode object, NoneType found
```

Here's an issue I found with a similar problem with CDLL: https://github.com/Fuyukai/Kyoukai/issues/19

**Comment by tkf** [comment]
Are you using `python-jl`?   FYI `python-jl --help` should print:

https://github.com/JuliaPy/pyjulia/blob/a90aa32945f9210ab620f47e280ac4f5f8aee29b/src/julia/python_jl.py#L10

But it'd be nice to find a way to do this in Windows.  I don't know how to.  I guess somebody has to write [the trick that PyCall does to find `libpython`](https://github.com/JuliaPy/PyCall.jl/blob/0b2dc20b22dfb286e031509aa89fcb76c3533cb9/src/startup.jl#L21-L36) in Python.

**Comment by tkf** [comment]
Actually, does

```python
from julia.api import LibJulia
api = LibJulia.load()
api.init_julia()
from julia import Main
```

work in Windows?

**Comment by JackDunnNZ** [comment]
I'm not using `python-jl` explicitly, I am calling `pyjulia` from Julia via PyCall (I am trying to use Documenter.jl to demonstrate usage of the pyjulia wrapper). But I guess that's what `python-jl` is basically doing from my limited understanding...

Here's what I get when I run that code:

```
>>> from julia.api import LibJulia
>>> api = LibJulia.load()
>>> api.init_julia()
>>> from julia import Main
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "C:\Users\iai\AppData\Local\Programs\Python\Python37\lib\site-packages\julia\core.py", line 253, in load_module
    JuliaMainModule(self, fullname))
  File "C:\Users\iai\AppData\Local\Programs\Python\Python37\lib\site-packages\julia\core.py", line 155, in __init__
    self._julia = loader.julia
  File "C:\Users\iai\AppData\Local\Programs\Python\Python37\lib\site-packages\julia\core.py", line 245, in julia
    self.__class__.julia = julia = Julia()
  File "C:\Users\iai\AppData\Local\Programs\Python\Python37\lib\site-packages\julia\core.py", line 1020, in __init__
    self._call(u"using PyCall")
  File "C:\Users\iai\AppData\Local\Programs\Python\Python37\lib\site-packages\julia\core.py", line 1054, in _call
    self.check_exception(src)
  File "C:\Users\iai\AppData\Local\Programs\Python\Python37\lib\site-packages\julia\core.py", line 1104, in check_exception
    .format(exception, src))
julia.core.JuliaError: Exception 'ArgumentError' occurred while calling julia code:
using PyCall
```

Thanks for the help, it's not a blocker for me as I can just avoid doing this on Windows for now, but let me know if I can help with any debugging or testing as needed

**Comment by JackDunnNZ** [comment]
I forgot to run `julia.install()` earlier, after doing that the example seems to work:

```
>>> from julia.api import LibJulia
>>> api = LibJulia.load()
>>> api.init_julia()
>>> from julia import Main
>>> Main.sind(10)
0.17364817766693036
```

**Comment by tkf** [comment]
Cool. So I think we need to do this automatically in Windows.

**Comment by tkf** [comment]
I think #289 solved this issue.  Can check that it works?

FYI you can install PyJulia from the `master` branch by `python3 -m pip install --user 'https://github.com/JuliaPy/pyjulia/archive/master.zip#egg=julia'`.  See also https://pyjulia.readthedocs.io/en/latest/installation.html#step-2-install-pyjulia

**Comment by JackDunnNZ** [comment]
Thanks, confirming it works!
