### ISSUE TITLE
pyjulia problem when loading package

### ISSUE THREAD

**Issue by jeremyrouot** [JuliaPy/pyjulia#309]
I installed the pyjulia module following the instructions given.

```
>>> julia.install()
[ Info: Julia version info
Julia Version 1.1.0
Commit 80516ca202* (2019-01-21 21:24 UTC)
Platform Info:
  OS: Linux (x86_64-redhat-linux)
      "Fedora release 30 (Thirty)"
  uname: Linux 5.1.16-300.fc30.x86_64 #1 SMP Wed Jul 3 15:06:51 UTC 2019 x86_64 x86_64
  CPU: Intel(R) Core(TM) i5-6440HQ CPU @ 2.60GHz: 
              speed         user         nice          sys         idle          irq
       #1  3204 MHz      36915 s        212 s      10827 s     325048 s       2239 s
       #2  3402 MHz      35255 s        197 s      11314 s     325961 s       2536 s
       #3  3315 MHz      40438 s        211 s      10309 s     315367 s       9032 s
       #4  3226 MHz      47509 s        313 s      10652 s     314448 s       2126 s
       
  Memory: 7.416706085205078 GB (693.796875 MB free)
  Uptime: 3774.0 sec
  Load Avg:  0.36083984375  0.3837890625  0.51220703125
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
Environment:
  JULIA_NUM_THREADS = 4
  JULIA_HOME = /usr/bin/
  FPATH = /home/fernand/.oh-my-zsh/plugins/z:/home/fernand/.oh-my-zsh/plugins/git:/home/fernand/.oh-my-zsh/functions:/home/fernand/.oh-my-zsh/completions:/usr/share/Modules/init/zsh-functions:/usr/local/share/zsh/site-functions:/usr/share/zsh/site-functions:/usr/share/zsh/5.7.1/functions
  HOME = /home/fernand
  MANPATH = :
  MATHEMATICA_HOME = /data/bin/mathe11p3
  MODULEPATH = /usr/share/Modules/modulefiles:/etc/modulefiles:/usr/share/modulefiles
  MODULEPATH_modshare = /usr/share/modulefiles:1:/usr/share/Modules/modulefiles:1:/etc/modulefiles:1
  MODULESHOME = /usr/share/Modules
  PATH = /usr/libexec/python3-sphinx:/usr/share/Modules/bin:/usr/lib64/ccache:/usr/local/bin:/usr/bin
  PATH_modshare = /bin:1:/usr/sbin:1:/var/lib/snapd/snap/bin:1:/usr/bin:1:/home/fernand/bin:1:/usr/local/sbin:1:/usr/libexec/python3-sphinx:1:/usr/share/Modules/bin:1:/usr/lib64/ccache:1:/usr/local/bin:1
  PROFILEHOME = 
  TERM = xterm-256color
  XDG_SEAT_PATH = /org/freedesktop/DisplayManager/Seat0
  XDG_SESSION_PATH = /org/freedesktop/DisplayManager/Session0
  TAPENADE_HOME = /data/bin/tapenade_3.14
  JULIA_HOME = /usr/bin/
[ Info: Julia executable: /usr/bin/julia
[ Info: Trying to import PyCall...
┌ Info: PyCall is already installed and compatible with Python executable.
│ 
│ PyCall:
│     python: python3
│     libpython: /usr/lib64/libpython3.7m.so.1.0
│ Python:
│     python: /usr/bin/python3
└     libpython: /usr/lib64/libpython3.7m.so.1.0
```

Here is the error that I got:

```
>>> from julia import Base
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "/home/fernand/.local/lib/python3.7/site-packages/julia/core.py", line 255, in load_module
    elif isafunction(self.julia, juliapath):
  File "/home/fernand/.local/lib/python3.7/site-packages/julia/core.py", line 246, in julia
    self.__class__.julia = julia = Julia()
  File "/home/fernand/.local/lib/python3.7/site-packages/julia/core.py", line 953, in __init__
    jlinfo = JuliaInfo.load(runtime)
  File "/home/fernand/.local/lib/python3.7/site-packages/julia/core.py", line 437, in load
    retcode, [julia, "-e", "..."], stdout, stderr
subprocess.CalledProcessError: Command '['julia', '-e', '...']' returned non-zero exit status 1.
>>> 
```

**Comment by tkf** [comment]
You can debug it by something like this (untested):

```python
try:
    from julia import Base
except Exception as err:
    print("STDOUT")
    print(err.stdout)
    print("STDERR")
    print(err.stderr)
```

**Comment by jeremyrouot** [comment]
indeed, missing library: libjulia
