### ISSUE TITLE
PyJulia seems to fail with Docker julia:latest

### ISSUE THREAD

**Issue by opus111** [JuliaPy/pyjulia#317]
This is simple code that works on OSX.  Code fails on initial call to Julia(compiled_modules=False).  No application Julia code has been called yet

```
Traceback (most recent call last):
  File "/app/shared/src/ner/tc2/go.py", line 36, in <module>
    tc2.create(args)
  File "/app/shared/src/ner/tc2/tc2.py", line 28, in create
    j = Julia(compiled_modules=False) #, sysimage=args.tc2_sysimage)
  File "/usr/local/lib/python3.7/dist-packages/julia/core.py", line 1011, in __init__
    self._call(u"using PyCall")
  File "/usr/local/lib/python3.7/dist-packages/julia/core.py", line 1082, in _call
    self.check_exception(src)
  File "/usr/local/lib/python3.7/dist-packages/julia/core.py", line 1132, in check_exception
    .format(exception, src))
julia.core.JuliaError: Exception 'ArgumentError' occurred while calling julia code:
using PyCall
```

Here is the Dockerfile used to create the image
```
FROM julia:latest

WORKDIR /app

COPY requirements.txt /app

RUN apt-get update
RUN apt-get install python3 python3-pip -y
RUN pip3 install --upgrade pip
RUN pip3 install --trusted-host pypi.python.org -r requirements.txt
RUN python3 -m pip install julia

ENV PYTHONPATH=/app/shared/src
```

**Comment by tkf** [comment]
Did you do `julia.install()`? https://pyjulia.readthedocs.io/en/latest/installation.html#step-3-install-julia-packages-required-by-pyjulia

**Comment by opus111** [comment]
Yep!  That was it.  Thank you for the quick help, and sorry to bother you
P
