### ISSUE TITLE
FileNotFoundError: [WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by hugo-tam** [JuliaPy/pyjulia#328]
Hi,

I looked into the two other issues with the same title (among other issues in this repository) but I don't think the solution applies to my issue - So I'm opening a new one.  (FYI #114 and #267).  Many thanks in advance.

Versions:
- `Python` 3.7.4
- `PyJulia` 0.4.1
- `Julia` 1.1.1
- `PyCall` 1.91.2
- `OS` Windows 8.1

I did:
1. Install PyJulia using pip install
2. Run `import julia` successfully in Python
3. Run `julia.install("C:\\JuliaPro-1.1.1.1\\Julia-1.1.1\\bin\\julia.exe") successfully with the following log

```
[ Info: Julia version info
Julia Version 1.1.1
Commit 55e36cc308 (2019-05-16 04:10 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
      Microsoft Windows [Version 6.3.9600]
  CPU: Intel(R) Core(TM) i5-4200U CPU @ 1.60GHz: 
              speed         user         nice          sys         idle          irq
       #1  1600 MHz     200718            0       106234      2096625         2406  ticks
       #2  1600 MHz     205125            0       106953      2091078         8156  ticks
       #3  1600 MHz     243421            0       107343      2052390         1562  ticks
       #4  1600 MHz     210765            0        99421      2092968         1375  ticks       
  Memory: 7.898242950439453 GB (4098.8359375 MB free)
  Uptime: 2403.0 sec
  Load Avg:  0.0  0.0  0.0
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, haswell)
Environment:
  HOMEDRIVE = C:
  HOMEPATH = \Users\3.14
  JUNORC_PATH = C:\JuliaPro-1.1.1.1\.atom
  PATH = **omitted - lots of paths**;
[ Info: Julia executable: C:\JuliaPro-1.1.1.1\Julia-1.1.1\bin\julia.exe
[ Info: Trying to import PyCall...
┌ Info: PyCall is already installed and compatible with Python executable.
│ 
│ PyCall:
│     python: C:\Project\venv\Scripts\python.exe
│     libpython: C:\Users\3.14\AppData\Local\Programs\Python\Python37\python37.dll
│ Python:
│     python: C:\Project\venv\Scripts\python.exe
└     libpython: C:\Users\3.14\AppData\Local\Programs\Python\Python37\python37.dll
```

However, it fails when I try to run
`from julia import Base`
which gives me the following error:
```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.2.1\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "C:\Users\3.14\AppData\Roaming\Python\Python37\site-packages\julia\core.py", line 255, in load_module
    elif isafunction(self.julia, juliapath):
  File "C:\Users\3.14\AppData\Roaming\Python\Python37\site-packages\julia\core.py", line 246, in julia
    self.__class__.julia = julia = Julia()
  File "C:\Users\3.14\AppData\Roaming\Python\Python37\site-packages\julia\core.py", line 953, in __init__
    jlinfo = JuliaInfo.load(runtime)
  File "C:\Users\3.14\AppData\Roaming\Python\Python37\site-packages\julia\core.py", line 425, in load
    **popen_kwargs)
  File "C:\Users\3.14\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "C:\Users\3.14\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

The other way round works with Julia calling Python using PyCall.

**Comment by tkf** [comment]
It looks like PyJulia is failed to find the `julia` executable. Maybe executing

```python
from julia import Julia
julia.Julia(runtime=r"C:\JuliaPro-1.1.1.1\Julia-1.1.1\bin\julia.exe")
```

before `from import Base` helps. See: https://pyjulia.readthedocs.io/en/latest/usage.html#low-level-interface

**Comment by hugo-tam** [comment]
Unfortunately I got the same error of file not found.

Not trying to something too complicated, I experimented the high-level interface by adding the Path environment variable and it works.  So I'll stick with this approach.

Many thanks for your help.
