### ISSUE TITLE
FileNotFoundError: [WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by queenk77** [JuliaPy/pyjulia#330]
$ ./openshs start --context morning -p
Starting the morning context.
What's the starting time? [2016-02-01 08:00:00]:
Traceback (most recent call last):
  File "./openshs", line 165, in <module>
    main()
  File "C:\Users\lilak\AppData\Local\Programs\Python\Python37\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\lilak\AppData\Local\Programs\Python\Python37\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "C:\Users\lilak\AppData\Local\Programs\Python\Python37\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\lilak\AppData\Local\Programs\Python\Python37\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\lilak\AppData\Local\Programs\Python\Python37\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "./openshs", line 115, in start
    subprocess.call(["primusrun", "blender", CONTEXTS[context]['exe']], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
  File "C:\Users\lilak\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 323, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Users\lilak\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "C:\Users\lilak\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

Please help!

**Comment by tkf** [comment]
See #267

**Comment by queenk77** [comment]
I did install pycall and julia but it the same error occurs 
Can you please tell me how can i fix this?

**Comment by tkf** [comment]
Did you do https://github.com/JuliaPy/pyjulia/issues/267#issuecomment-480123140 ? Did you also try `Pkg.build("PyCall", verbose=true)`? What was the output? Also, please quote any code snippets and logs in triple backquote

`````
```
like this
```
`````
