### ISSUE TITLE
Julia not found when julia.install()

### ISSUE THREAD

**Issue by hect1995** [JuliaPy/pyjulia#357]
I have Julia v.0.6.4 downloaded and I do not accomplish to link it using PyCall v.0.4.1. I have added my julia executable to PATH: `export PATH="$HOME/JuliaPro-0.6.4.1:$PATH"` as my julia executable is in `$HOME/JuliaPro-0.6.4.1/julia`. After sourcing `.bashrc` and trying to julia.install I get:
```
julia.install()
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/developer/anaconda3/envs/motionplanningthesishector/lib/python3.7/site-packages/julia/tools.py", line 61, in install
    raise JuliaNotFound(julia, kwargname="julia")
julia.core.JuliaNotFound: Julia executable `julia` cannot be found.
If you have installed Julia, make sure Julia executable is in the
system PATH.  Alternatively, specify file path to the Julia executable
using `julia` keyword argument.
If you have not installed Julia, download Julia from
https://julialang.org/downloads/ and install it.
```

**Comment by tkf** [comment]
In principle, this should work:

```python
import julia
j = julia.Julia(runtime="/home/developer/JuliaPro-0.6.4.1/Julia/bin/julia")
from julia import Main
Main.include("PATH/TO/setup.jl")
```

I'm not sure what is going on with the segmentation fault.  Can you put the rest of the stacktrace?  You can also enable debug-level messages with `julia.Julia(..., debug=True)`.

**Comment by hect1995** [comment]
```
j = julia.Julia(runtime="/home/developer/JuliaPro-0.6.4.1/Julia/bin/julia",debug=True)
DEBUG 
DEBUG Debug-level logging is enabled for PyJulia.
DEBUG PyJulia version: 0.4.1
DEBUG 
DEBUG pyprogramname = /home/developer/anaconda3/envs/motionplanningthesishector/bin/python
DEBUG sys.executable = /home/developer/anaconda3/envs/motionplanningthesishector/bin/python
DEBUG bindir = /home/developer/JuliaPro-0.6.4.1/Julia/bin
DEBUG libjulia_path = /home/developer/JuliaPro-0.6.4.1/Julia/bin/../lib/libjulia.so.0.6
DEBUG py_libpython = None
DEBUG jl_libpython = /home/developer/anaconda3/envs/motionplanningthesishector/lib/libpython3.7m.so.1.0
DEBUG use_separate_cache = True
DEBUG calling jl_init_with_image(/home/developer/anaconda3/envs/motionplanningthesishector/lib/python3.7/site-packages/julia/fake-julia, /home/developer/JuliaPro-0.6.4.1/Julia/lib/julia/sys.so)
DEBUG seems to work...
DEBUG exception occured? None
DEBUG exception occured? None
DEBUG exception occured? None
DEBUG exception occured? None
DEBUG exception occured? None
DEBUG exception occured? None
DEBUG exception occured? None
DEBUG exception occured? None
DEBUG exception occured? None
DEBUG exception occured? None
DEBUG exception occured? None
DEBUG exception occured? None
DEBUG 
signal (11): Segmentation fault
while loading no file, in expression starting on line 0
```

**Comment by hect1995** [comment]
I have updated my Julia version to 1.0.5 and updated PyCall to 0.5.1 and still same output:
```
j = julia.Julia(runtime="/home/developer/JuliaPro-1.0.5-2/Julia/bin/julia", compiled_modules=False, debug=True)
DEBUG 
DEBUG Debug-level logging is enabled for PyJulia.
DEBUG PyJulia version: 0.5.1
DEBUG 
DEBUG pyprogramname = /usr/bin/python3
DEBUG sys.executable = /home/developer/anaconda3/envs/motionplanningthesishector/bin/python
DEBUG bindir = /home/developer/JuliaPro-1.0.5-2/Julia/bin
DEBUG libjulia_path = /home/developer/JuliaPro-1.0.5-2/Julia/bin/../lib/libjulia.so.1
DEBUG py_libpython = None
DEBUG jl_libpython = /usr/lib/x86_64-linux-gnu/libpython3.6m.so.1.0
DEBUG is_compatible_python = False
DEBUG compiled_modules = 'no'
DEBUG argv_list = [b'/home/developer/anaconda3/envs/motionplanningthesishector/bin/python', b'--compiled-modules', b'no']
DEBUG argc = c_int(3)
DEBUG jl_parse_opts called
DEBUG argc = c_int(0)
DEBUG calling jl_init_with_image(/home/developer/JuliaPro-1.0.5-2/Julia/bin, /home/developer/JuliaPro-1.0.5-2/Julia/lib/julia/sys.so)
DEBUG seems to work...
DEBUG exception occured? None
DEBUG exception occured? None
DEBUG exception occured? None
DEBUG exception occured? None
DEBUG exception occured? None
DEBUG exception occured? None
DEBUG exception occured? None
DEBUG exception occured? None
DEBUG exception occured? None
DEBUG 
signal (11): Segmentation fault
in expression starting at no file:0
```

**Comment by tkf** [comment]
> if I run the same commands over the Python from the Terminal (before I was using PyCharm) it works, but the Python executable used is the same in both places, do you know what may happen?

It's hard to tell without stacktrace and/or debug log. Maybe different environment variable?

> they appear in `/home/developer/.julia/packages`

This does not necessary mean that the packages are importable. Only the packages that are included in `Project.toml` of the current environment are importable (roughly speaking). (assuming that you are using Julia >= 1 now)

You can check it by

```python
>>> from julia import Pkg
>>> Pkg.status()
```

in Python REPL or

```julia
julia> using Pkg

julia> Pkg.status()
```

in Julia REPL.


Anyway, the correct solution here is to follow what the error message said

> ```
> Run `Pkg.add(\"JuMP\")` to install the JuMP package."
> ```

So run `Pkg.add("JuMP")` and other dependencies.

**Comment by hect1995** [comment]
But I have them actually installed:
```
julia> Pkg.status()
    Status `~/.juliapro/JuliaPro_v1.0.5-2/environments/v1.0/Project.toml`
  [c52e3926] Atom v0.11.2
  [9961bab8] Cbc v0.6.6
  [a6e380b2] ControlSystems v0.5.6
  [a93c6f00] DataFrames v0.20.0
  [864edb3b] DataStructures v0.17.6
  [7073ff75] IJulia v1.20.0
  [b6b21f68] Ipopt v0.6.1
  [682c06a0] JSON v0.21.0
  [4076af6c] JuMP v0.20.1
  [2ddba703] Juniper v0.5.2
  [e5e0dc1b] Juno v0.7.2
  [15e1cf62] NPZ v0.4.0
  [b8a86587] NearestNeighbors v0.4.4
  [91a5bcdd] Plots v0.28.2
  [438e738f] PyCall v1.91.2
  [d330b81b] PyPlot v2.8.2
  [37e2e46d] LinearAlgebra 
  [8dfed614] Test 
```

If I run it from my Julia environment I have no problem as all the packages are installed. From the Terminal when doing : 
```
import julia
j = julia.Julia(runtime="/home/developer/JuliaPro-1.0.5-2/Julia/bin/julia", compiled_modules=False)
from julia import Main
Main.include("setup.jl")
```


 I get:
```
 Main.include("setup.jl")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: Julia exception: LoadError: LoadError: LoadError: LoadError: LoadError: CodecBzip2.jl is not installed properly, run Pkg.build("CodecBzip2") and restart Julia.
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] top-level scope at /home/developer/.julia/packages/CodecBzip2/T5yr7/src/CodecBzip2.jl:21
 [3] include at ./boot.jl:317 [inlined]
 [4] include_relative(::Module, ::String) at ./loading.jl:1044
 [5] _require(::Base.PkgId) at ./loading.jl:986
 [6] require(::Base.PkgId) at ./loading.jl:858
 [7] require(::Module, ::Symbol) at ./loading.jl:853
 [8] include at ./boot.jl:317 [inlined]
 [9] include_relative(::Module, ::String) at ./loading.jl:1044
 [10] include at ./sysimg.jl:29 [inlined]
 [11] include(::String) at /home/developer/.julia/packages/MathOptInterface/DmQBj/src/MathOptInterface.jl:1
 [12] top-level scope at none:0
 [13] include at ./boot.jl:317 [inlined]
 [14] include_relative(::Module, ::String) at ./loading.jl:1044
 [15] _require(::Base.PkgId) at ./loading.jl:986
 [16] require(::Base.PkgId) at ./loading.jl:858
 [17] require(::Module, ::Symbol) at ./loading.jl:853
 [18] include at ./boot.jl:317 [inlined]
 [19] include_relative(::Module, ::String) at ./loading.jl:1044
 [20] _require(::Base.PkgId) at ./loading.jl:986
 [21] require(::Base.PkgId) at ./loading.jl:858
 [22] require(::Module, ::Symbol) at ./loading.jl:853
 [23] include at ./boot.jl:317 [inlined]
 [24] include_relative(::Module, ::String) at ./loading.jl:1044
 [25] include(::Module, ::String) at ./sysimg.jl:29
 [26] include(::String) at ./client.jl:392
 [27] #invokelatest#1(::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::Function, ::Any, ::Any, ::Vararg{Any,N} where N) at ./essentials.jl:697
 [28] invokelatest(::Any, ::Any, ::Vararg{Any,N} where N) at ./essentials.jl:696
 [29] _pyjlwrap_call(::Function, ::Ptr{PyCall.PyObject_struct}, ::Ptr{PyCall.PyObject_struct}) at /home/developer/.julia/packages/PyCall/ttONZ/src/callback.jl:28
 [30] pyjlwrap_call(::Ptr{PyCall.PyObject_struct}, ::Ptr{PyCall.PyObject_struct}, ::Ptr{PyCall.PyObject_struct}) at /home/developer/.julia/packages/PyCall/ttONZ/src/callback.jl:49
in expression starting at /home/developer/.julia/packages/CodecBzip2/T5yr7/src/CodecBzip2.jl:20
in expression starting at /home/developer/.julia/packages/MathOptInterface/DmQBj/src/FileFormats/FileFormats.jl:6
in expression starting at /home/developer/.julia/packages/MathOptInterface/DmQBj/src/MathOptInterface.jl:127
in expression starting at /home/developer/.julia/packages/JuMP/MsUSY/src/JuMP.jl:16
in expression starting at /home/developer/thesismotionplanning/Planner/optimizers/H-OBCA/setup.jl:35
```
Line 35 in `setup.jl` is `using JuMP, Ipopt, PyPlot, NearestNeighbors, ControlSystems, NPZ, JSON`
and as I said all these packages I have them installed.
BTW: I am using a conda environment
