### ISSUE TITLE
cannot evalulate function with 2D numpy.ndarray input

### ISSUE THREAD

**Issue by hackermd** [JuliaPy/pyjulia#41]
When calling a custom Julia function from Python and parsing a numpy array as input, it only works when the dimensions of the array are small.

``` python
import os
import numpy as np
import julia

# provide absolute path to r module file
libpath = 'path/to/test/file' 
module_file = 'test.jl'
module_file = os.path.join(libpath, module_file)

# start the julia engine and include jl file
print 'start julia engine'
j = julia.Julia()  # starting the julia engine this takes forever!
print 'include julia file: "%s"' % module_file
j.eval('include("{0}")'.format(module_file))

# call the jl module with some arguments and assign it to a variable
dims = (10, 10)  # works with (5, 5)
py_var = np.random.random(dims)
print 'evaluate julia function and assign result to variable'
jl_var = j.eval('test({0})'.format(py_var))

print 'type of variable:\n{0}'.format(type(jl_var))
print 'dimensions of variable:\n{0}'.format(jl_var.shape)
print 'value of variable:\n{0}'.format(jl_var)
print 'type of elements in variable:\n{0}'.format(jl_var.dtype)

np.testing.assert_array_equal(jl_var, py_var,
                              err_msg='input and output are not identical')

# when dims = (5, 5) raises AssertionError despite correct type, dimensions, and values???
```

This is the content of the `test.jl` file:

``` julia
function test(x)
     return x
end
```

When `dims = (10, 10)` the above Python code produces the following error message:

```
Traceback (most recent call last):
  File "test_j_module.py", line 21, in <module>
    jl_var = j.eval('test({0})'.format(py_var))
  File "/usr/local/lib/python2.7/site-packages/julia/core.py", line 329, in call
    .format(exception_type, exception_msg, src))
julia.core.JuliaError: Exception 'ErrorException' ocurred while calling julia code:
<couldn't get stack>

Code:
test([[ 0.20682803  0.04704934  0.13274106  0.05469292  0.40254676  0.18466478
   0.84020545  0.99678851  0.47026452  0.61415764]
 [ 0.00901351  0.00545614  0.36920023  0.59153858  0.93464972  0.5847787
   0.88878481  0.45640786  0.48818201  0.65426845]
 [ 0.79333042  0.06071264  0.35143529  0.15739708  0.38740339  0.63253983
   0.13512716  0.67442572  0.99706677  0.12753637]
 [ 0.26065309  0.00170454  0.28043126  0.40828326  0.86559628  0.60525831
   0.96192417  0.91599325  0.67131462  0.97354081]
 [ 0.42094702  0.82631545  0.44081515  0.95666598  0.65161472  0.58373058
   0.20209026  0.17087424  0.6004557   0.48976695]
 [ 0.71146331  0.42216148  0.80070431  0.08453404  0.72486401  0.84377365
   0.58063987  0.66267037  0.69185328  0.90252447]
 [ 0.95943342  0.78431303  0.36191132  0.23996024  0.0625853   0.68399853
   0.96369497  0.69657076  0.05399353  0.86838642]
 [ 0.66141604  0.00102945  0.31846223  0.80442309  0.81558502  0.52736737
   0.07361813  0.74874239  0.3049418   0.73352948]
 [ 0.40454631  0.54091448  0.57932001  0.55639143  0.99712401  0.96816375
   0.16446963  0.95342441  0.72510795  0.74854267]
 [ 0.66389913  0.07991279  0.817699    0.65261875  0.57849456  0.53964192
   0.80881346  0.8784131   0.1920992   0.41979808]])
```

When `dims = (5, 5)` it produces the following error message:

```
Traceback (most recent call last):
  File "test_j_module.py", line 31, in <module>
    err_msg='input and output are not identical')
  File "/usr/local/lib/python2.7/site-packages/numpy/testing/utils.py", line 739, in assert_array_equal
    verbose=verbose, header='Arrays are not equal')
  File "/usr/local/lib/python2.7/site-packages/numpy/testing/utils.py", line 665, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not equal
input and output are not identical
(mismatch 100.0%)
 x: array([[ 0.618968,  0.501059,  0.143219,  0.721154,  0.134409],
       [ 0.845478,  0.100637,  0.184674,  0.994752,  0.030494],
       [ 0.508936,  0.699266,  0.678141,  0.08459 ,  0.622509],...
 y: array([[ 0.618968,  0.501059,  0.143219,  0.721154,  0.134409],
       [ 0.845478,  0.100637,  0.184674,  0.994752,  0.030494],
       [ 0.508936,  0.699266,  0.678141,  0.08459 ,  0.622509],...
```

**Comment by HackerMD** [comment]
I installed as follows: `pip install julia`

**Comment by jakebolewski** [comment]
@HackerMD could you post (or link to a gist) the output of `versioninfo(true)`.  It would be useful to see what version of Julia / PyCall you are using.

**Comment by HackerMD** [comment]
Output of `versioninfo(true)`:

```
Julia Version 0.3.8-pre+1
Commit dcf61ab (2015-03-23 21:40 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin14.1.0)
  CPU: Intel(R) Core(TM) i7-4960HQ CPU @ 2.60GHz
  WORD_SIZE: 64
  uname: Darwin 14.3.0 Darwin Kernel Version 14.3.0: Mon Mar 23 11:59:05 PDT 2015; root:xnu-2782.20.48~5/RELEASE_X86_64 x86_64 i386
Memory: 16.0 GB (9112.07421875 MB free)
Uptime: 181986.0 sec
Load Avg:  1.82421875  1.68115234375  1.74169921875
Intel(R) Core(TM) i7-4960HQ CPU @ 2.60GHz: 
       speed         user         nice          sys         idle          irq
#1  2600 MHz      64916 s          0 s      64217 s     881306 s          0 s
#2  2600 MHz       1856 s          0 s       1128 s    1007417 s          0 s
#3  2600 MHz      46793 s          0 s      23577 s     940045 s          0 s
#4  2600 MHz       2024 s          0 s       1385 s    1006989 s          0 s
#5  2600 MHz      46857 s          0 s      23603 s     939950 s          0 s
#6  2600 MHz       2015 s          0 s       1345 s    1007033 s          0 s
#7  2600 MHz      46735 s          0 s      23536 s     940134 s          0 s
#8  2600 MHz       2014 s          0 s       1358 s    1007018 s          0 s

  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
Environment:
  XPC_FLAGS = 0x0
  TERM = xterm-256color
  HOME = /Users/mdh
  PATH = /Users/mdh/labcode/iBRAIN_tools:/Users/mdh/tmt/tmt/corilla:/Users/mdh/tmt/tmt/datafusion:/Users/mdh/tmt/tmt/illuminati:/Users/mdh/tmt/tmt/align:/Users/mdh/tmt/tmt/visi:/Users/mdh/jterator/src/jterator:/usr/local/opt/coreutils/libexec/gnubin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/texbin
  MANPATH = /usr/local/opt/coreutils/libexec/gnuman:
  JAVA_HOME = /Library/Internet\ Plug-Ins/JavaAppletPlugin.plugin/Contents/Home
  PYTHONPATH = :/Users/mdh/jterator/src:/Users/mdh/jterator/api/python:/Users/mdh/plia/python:/Users/mdh/tmt:/Users/mdh/tmt/tmt:/Users/mdh
  MATLAB_HOME = /Applications/MATLAB_R2015a.app
  MATLABPATH = :/Users/mdh/jterator/api/matlab:/Users/mdh/plia/matlab/
  JULIA_LOAD_PATH = :/Users/mdh/jterator/api/julia/jtapi
  WORKON_HOME = /Users/mdh/Envs

Package Directory: /Users/mdh/.julia/v0.3

^[[A^[[B^[[B^[[D4 required packages:
 - HDF5                          0.4.13
 - MATLAB                        0.1.2
 - PyCall                        0.7.5
 - YAML                          0.1.8
9 additional packages:
 - BinDeps                       0.3.9
 - Blosc                         0.1.2
 - Codecs                        0.1.3
 - Compat                        0.3.7
 - Dates                         0.3.2
 - Homebrew                      0.1.14
 - JSON                          0.4.2
 - SHA                           0.0.4
 - URIParser                     0.0.5
```

**Comment by HackerMD** [comment]
Any idea? Would be great if this could be fixed.

**Comment by tkf** [comment]
This issue is pretty old... But:

```julia
jl_var = j.eval('test({0})'.format(py_var))
```

is not the right way to do it.  Use:

```julia
jl_var = j.eval('test')(py_var)
```

Also, use `from julia import Main` instead of `j = julia.Julia()` in PyJulia 0.2.

Closing...
