### ISSUE TITLE
Exception when trying to acces submodules of Main

### ISSUE THREAD

**Issue by paulmelis** [JuliaPy/pyjulia#414]
I was trying to explore what Python functions are available as submodules of `Main`, especially the `PyCall` module, but apparently that isn't possible? Or is this a bug?

```
Python 3.8.5 (default, Jul 27 2020, 08:42:51) 
[GCC 10.1.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from julia.api import Julia
>>> j=Julia()
>>> from julia import Main
>>> dir(Main)
['Base', 'Core', 'PyCall', '__doc__', '__loader__', '__name__', '__package__', '__spec__', '_julia']
>>> dir(Main.Base)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/melis/.local/lib/python3.8/site-packages/julia/core.py", line 176, in __getattr__
    return self.__try_getattr(name)
  File "/home/melis/.local/lib/python3.8/site-packages/julia/core.py", line 191, in __try_getattr
    if self._julia.isdefined(realname):
  File "/home/melis/.local/lib/python3.8/site-packages/julia/core.py", line 645, in isdefined
    raise ValueError(
ValueError: `julia.isdefined(name)` requires at least one dot in `name`.
>>> 

```

**Comment by tkf** [comment]
Yes, it's a bug.

**Comment by torfjelde** [comment]
Any updates on this? Currently running into the same issue :confused:
