### ISSUE TITLE
Error loading custom module

### ISSUE THREAD

**Issue by arbenede** [JuliaPy/pyjulia#446]
I am using Julia 1.6.1 and python 3.5 running under an Ubuntu VM. When I try to load a custom Julia module:
```
from julia.api import Julia
jl = Julia(compiled_modules=False)

from julia import Base
from julia import Main
Main.eval('push!(LOAD_PATH, "<path to MyModule.jl>")')
Main.eval('using MyModule')
``` 
I get the error:
```
>>> Main.eval("using MyModule")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/vagrant/workspace/venv3/lib/python3.5/site-packages/julia/core.py", line 605, in eval
    ans = self._call(src)
  File "/vagrant/workspace/venv3/lib/python3.5/site-packages/julia/core.py", line 538, in _call
    self.check_exception(src)
  File "/vagrant/venv3/lib/python3.5/site-packages/julia/core.py", line 588, in check_exception
    .format(exception, src))
julia.core.JuliaError: Exception 'ArgumentError: Package MyModule not found in current path:
- Run `import Pkg; Pkg.add("MyModule")` to install the MyModule package.
' occurred while calling julia code:
using MyModule
```
I get the same error if I run `jl.using("MyModule")` instead of `Main.eval('using MyModule')`. Interestingly, I get the same error when I use `PythonCall.jl`...!? 
By the way I need to call `jl = Julia(compiled_modules=False)` since I am running a statically linked Python interpreter. Any ideas?

**Comment by arbenede** [comment]
My bad! A pathname was wrong, as it often happens when you use a virtual machine...  I am closing the issue.
