### ISSUE TITLE
Default Conda_env statically linked to libpython?

### ISSUE THREAD

**Issue by axla-io** [JuliaPy/pyjulia#542]
Hi, I want to be able to use pyjulia, but I run into the following issue:

- I install PyCall
- I open the python executable installed in Conda_env and run julia.install(). This tells me that "PyCall is already installed and compatible with Python executable."
- I run from julia import Base and get an error saying:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 674, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/Users/me/.local/lib/python3.11/site-packages/julia/core.py", line 248, in load_module
    elif self.julia.isafunction(juliapath):
         ^^^^^^^^^^
  File "/Users/me/.local/lib/python3.11/site-packages/julia/core.py", line 239, in julia
    self.__class__.julia = julia = Julia()
                                   ^^^^^^^
  File "/Users/me/.local/lib/python3.11/site-packages/julia/core.py", line 489, in __init__
    raise UnsupportedPythonError(jlinfo)
julia.core.UnsupportedPythonError: It seems your Julia and PyJulia setup are not supported.

Julia executable:
    julia
Python interpreter and libpython used by PyCall.jl:
    /Users/me/.julia/Conda_env/bin/python
    /Users/me/.julia/Conda_env/lib/libpython3.11.dylib
Python interpreter used to import PyJulia and its libpython.
    /Users/me/.julia/Conda_env/bin/python
    /Users/me/.julia/Conda_env/lib/libpython3.11.dylib

Your Python interpreter "/Users/me/.julia/Conda_env/bin/python"
is statically linked to libpython.  Currently, PyJulia does not fully
support such Python interpreter.```

**Comment by mkitti** [comment]
What was the original Python you were trying to use?

**Comment by mkitti** [comment]
Also, have you considered https://github.com/JuliaPy/PythonCall.jl / juliacall ?
