### ISSUE TITLE
error starting up the Julia process

### ISSUE THREAD

**Issue by mandarup** [JuliaPy/pyjulia#65]
```
>>> import julia
>>> j = julia.Julia()
 ERROR: UndefVarError: dlpath not defined
 in eval(::Module, ::Any) at ./boot.jl:234
 in eval(::Module, ::Any) at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
 in process_options(::Base.JLOptions) at ./client.jl:239
 in _start() at ./client.jl:318
 in _start() at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
 Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/<username>/anaconda/lib/python2.7/site-packages/julia/core.py", line 244, in __init__
    raise JuliaError('error starting up the Julia process')
julia.core.JuliaError: error starting up the Julia process
```

it works if I start python from pyjulia root dir

```
cd path/to/pyjulia
python
>>> import julia
>>> j = julia.Julia()
>>> 
```

**Comment by stevengj** [comment]
How did you install `pyjulia`?  Did you do `sudo python setup.py install` as recommended in the README?

**Comment by mandarup** [comment]
yes

**Comment by mandarup** [comment]
as of 2017/12 this is working
