### ISSUE TITLE
Crashing and burning, the docker way

### ISSUE THREAD

**Issue by GunnarFarneback** [JuliaPy/pyjulia#73]
[This duplicates parts of the issues reported in #66 and its comments but should be fully reproducible.]

I have installed PyJulia in a fairly minimalistic docker build. Dockerfile:
```
FROM ubuntu:16.04

RUN apt-get update \
 && apt-get install -y python3 python3-dev python3-setuptools wget git bzip2

RUN cd /opt \
 && wget https://julialang.s3.amazonaws.com/bin/linux/x64/0.5/julia-0.5.0-linux-x86_64.tar.gz \
 && mkdir julia \
 && tar xvfz julia-0.5.0-linux-x86_64.tar.gz --strip-components 1 -C julia
ENV PATH /opt/julia/bin:$PATH

ENV PYTHON /usr/bin/python3
RUN julia -e 'Pkg.add("PyCall")'

RUN cd /opt \
 && git clone https://github.com/JuliaPy/pyjulia.git \
 && cd pyjulia \
 && python3 setup.py install
```
As far as I can tell it complies with the installation instructions in the README.

All the following examples are run in separate containers freshly started from the image specified above. Testing PyJulia right away gives a failure to locate fake-julia.
```
root@382813662d53:/# python3
Python 3.5.2 (default, Nov 17 2016, 17:05:23) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import julia
>>> j = julia.Julia()
WARNING: redefining constant JULIA_HOME
could not spawn `/usr/local/lib/python3.5/dist-packages/julia-0.1.1-py3.5.egg/julia/../fake-julia/julia -Cx86-64 -J/opt/julia/lib/julia/sys.so --compile=yes --depwarn=yes -O0 --output-ji /root/.julia/lib/pyjulia3-v0.5/PyCall.ji --output-incremental=yes --startup-file=no --history-file=no --color=no --eval 'while !eof(STDIN)
    eval(Main, deserialize(STDIN))
end
'`: no such file or directory (ENOENT)Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/julia-0.1.1-py3.5.egg/julia/core.py", line 353, in __init__
    self._call(u"using PyCall")
  File "/usr/local/lib/python3.5/dist-packages/julia-0.1.1-py3.5.egg/julia/core.py", line 392, in _call
    self.check_exception(src)
  File "/usr/local/lib/python3.5/dist-packages/julia-0.1.1-py3.5.egg/julia/core.py", line 412, in check_exception
    .format(exception_type, src))
julia.core.JuliaError: Exception 'UVError' occurred while calling julia code:
using PyCall
>>> 
root@382813662d53:/# ls /usr/local/lib/python3.5/dist-packages/julia-0.1.1-py3.5.egg
EGG-INFO  julia
```
Doesn't look like fake-julia is installed. Should it be?

First forcing a precompile of PyCall apparently eliminates the need for fake-julia but instead crashes with a segmentation fault.
```
root@f34ebf9ca732:/# julia -e "using PyCall"
root@f34ebf9ca732:/# python3
Python 3.5.2 (default, Nov 17 2016, 17:05:23) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import julia
>>> j = julia.Julia()
WARNING: redefining constant JULIA_HOME
InitError(:PyCall,PyError (:PyImport_ImportModule) <class 'SystemError'>
SystemError('initialization of _opcode did not return an extension module',)

signal (11): Segmentation fault
while loading no file, in expression starting on line 0
PyObject_Call at /usr/lib/x86_64-linux-gnu/libpython3.5m.so (unknown line)
macro expansion at /root/.julia/v0.5/PyCall/src/exception.jl:78 [inlined]
#_pycall#62 at /root/.julia/v0.5/PyCall/src/PyCall.jl:546
jl_call_method_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:189 [inlined]
jl_apply_generic at /home/centos/buildbot/slave/package_tarball64/build/src/gf.c:1942
jl_apply at /home/centos/buildbot/slave/package_tarball64/build/src/julia.h:1392 [inlined]
jl_f__apply at /home/centos/buildbot/slave/package_tarball64/build/src/builtins.c:547
_pycall at /root/.julia/v0.5/PyCall/src/PyCall.jl:534
jl_call_method_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:189 [inlined]
jl_apply_generic at /home/centos/buildbot/slave/package_tarball64/build/src/gf.c:1942
jl_apply at /home/centos/buildbot/slave/package_tarball64/build/src/julia.h:1392 [inlined]
jl_f__apply at /home/centos/buildbot/slave/package_tarball64/build/src/builtins.c:547
#pycall#65 at /root/.julia/v0.5/PyCall/src/PyCall.jl:565
show at /root/.julia/v0.5/PyCall/src/exception.jl:39
unknown function (ip: 0x7f9cea309226)
jl_call_method_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:189 [inlined]
jl_apply_generic at /home/centos/buildbot/slave/package_tarball64/build/src/gf.c:1942
show_default at ./show.jl:130
unknown function (ip: 0x7f9cea307c26)
jl_call_method_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:189 [inlined]
jl_apply_generic at /home/centos/buildbot/slave/package_tarball64/build/src/gf.c:1942
show at ./show.jl:116
unknown function (ip: 0x7f9cea307686)
jl_call_method_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:189 [inlined]
jl_apply_generic at /home/centos/buildbot/slave/package_tarball64/build/src/gf.c:1942
jl_apply at /home/centos/buildbot/slave/package_tarball64/build/src/julia.h:1392 [inlined]
jl_show at /home/centos/buildbot/slave/package_tarball64/build/src/builtins.c:972
ffi_call_unix64 at /usr/lib/python3.5/lib-dynload/_ctypes.cpython-35m-x86_64-linux-gnu.so (unknown line)
ffi_call at /usr/lib/python3.5/lib-dynload/_ctypes.cpython-35m-x86_64-linux-gnu.so (unknown line)
_ctypes_callproc at /usr/lib/python3.5/lib-dynload/_ctypes.cpython-35m-x86_64-linux-gnu.so (unknown line)
unknown function (ip: 0x7f9f0c52afca)
PyObject_Call at python3 (unknown line)
PyEval_EvalFrameEx at python3 (unknown line)
unknown function (ip: 0x52d2e2)
PyEval_EvalFrameEx at python3 (unknown line)
PyEval_EvalFrameEx at python3 (unknown line)
PyEval_EvalCodeEx at python3 (unknown line)
unknown function (ip: 0x4ebd37)
PyObject_Call at python3 (unknown line)
unknown function (ip: 0x4f413d)
PyObject_Call at python3 (unknown line)
unknown function (ip: 0x54d358)
unknown function (ip: 0x55d17b)
PyObject_Call at python3 (unknown line)
PyEval_EvalFrameEx at python3 (unknown line)
unknown function (ip: 0x52d2e2)
PyEval_EvalCode at python3 (unknown line)
unknown function (ip: 0x5fd2c1)
PyRun_InteractiveOneObject at python3 (unknown line)
PyRun_InteractiveLoopFlags at python3 (unknown line)
unknown function (ip: 0x4585cf)
unknown function (ip: 0x4cf269)
main at python3 (unknown line)
__libc_start_main at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
_start at python3 (unknown line)
Allocations: 2218551 (Pool: 2217599; Big: 952); GC: 1
Segmentation fault (core dumped)
```
Adding a rebuild of PyCall takes us back to the first failure.
```
root@c330a94202e3:/# julia -e 'using PyCall; Pkg.build("PyCall")'
INFO: Building Conda
INFO: Building PyCall
INFO: PyCall is using /usr/bin/python3 (Python 3.5.2) at /usr/bin/python3, libpython = libpython3.5m
root@c330a94202e3:/# python3
Python 3.5.2 (default, Nov 17 2016, 17:05:23) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import julia
>>> j = julia.Julia()
WARNING: redefining constant JULIA_HOME
could not spawn `/usr/local/lib/python3.5/dist-packages/julia-0.1.1-py3.5.egg/julia/../fake-julia/julia -Cx86-64 -J/opt/julia/lib/julia/sys.so --compile=yes --depwarn=yes -O0 --output-ji /root/.julia/lib/pyjulia3-v0.5/PyCall.ji --output-incremental=yes --startup-file=no --history-file=no --color=no --eval 'while !eof(STDIN)
    eval(Main, deserialize(STDIN))
end
'`: no such file or directory (ENOENT)Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/julia-0.1.1-py3.5.egg/julia/core.py", line 353, in __init__
    self._call(u"using PyCall")
  File "/usr/local/lib/python3.5/dist-packages/julia-0.1.1-py3.5.egg/julia/core.py", line 392, in _call
    self.check_exception(src)
  File "/usr/local/lib/python3.5/dist-packages/julia-0.1.1-py3.5.egg/julia/core.py", line 412, in check_exception
    .format(exception_type, src))
julia.core.JuliaError: Exception 'UVError' occurred while calling julia code:
using PyCall
```
For what it's worth, copying fake-julia into the installed egg does at least allow basic usage to work, although the JULIA_HOME warning is still there.
```
root@c98507fe7aef:/# cp -r /opt/pyjulia/fake-julia /usr/local/lib/python3.5/dist-packages/julia-0.1.1-py3.5.egg
root@c98507fe7aef:/# python3
Python 3.5.2 (default, Nov 17 2016, 17:05:23) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import julia
>>> j = julia.Julia() 
WARNING: redefining constant JULIA_HOME
>>> j.sind(90)
1.0
```

**Comment by colinfang** [comment]
I have a similar problem with Python 2

Docker file

```docker
FROM ubuntu:16.04
RUN echo '2017-01-10'
 
RUN apt-get update && \
    apt-get install -qq python python-pip sudo wget python-dev libblas-dev liblapack-dev libatlas-base-dev gfortran wget git cmake libzmq3-dev
 
# https://github.com/docker-library/julia/blob/master/Dockerfile
ENV JULIA_PATH /usr/local/julia
 
RUN mkdir $JULIA_PATH && \
    wget -nv -O julia.tar.gz "https://julialang.s3.amazonaws.com/bin/linux/x64/0.5/julia-0.5.0-linux-x86_64.tar.gz" && \
    tar -xzf julia.tar.gz -C $JULIA_PATH --strip-components 1 && \
    rm julia.tar.gz*
 
ENV PATH $JULIA_PATH/bin:$PATH
 
# Easy debug.
RUN pip install ipython
 
RUN pip install -I git+git://github.com/JuliaPy/pyjulia.git
 
RUN julia -e 'Pkg.init()'
RUN julia -e 'Pkg.add("PyCall")'
RUN julia -e 'using PyCall'
```

In container

```
In [1]: import julia

In [2]: julia.Julia(debug=True)
JULIA_HOME = /usr/local/julia/bin,  libjulia_path = /usr/local/julia/bin/../lib/libjulia.so.0.5
calling jl_init(/usr/local/julia/bin)
seems to work...
exception occured? None
WARNING: redefining constant JULIA_HOME
exception occured? None
exception occured? None
exception occured? None
exception occured? 139896958598832
Retrieving exception infos...
libjulia stderr = 139896924142320
InitError(:PyCall,PyError (:PyImport_ImportModule) <type 'exceptions.SystemError'>
SystemError('dynamic module not initialized properly',)

signal (11): Segmentation fault
while loading no file, in expression starting on line 0
PyObject_Call at /usr/lib/x86_64-linux-gnu/libpython2.7.so (unknown line)
macro expansion at /root/.julia/v0.5/PyCall/src/exception.jl:78 [inlined]
#_pycall#66 at /root/.julia/v0.5/PyCall/src/PyCall.jl:546
jl_call_method_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:189 [inlined]
jl_apply_generic at /home/centos/buildbot/slave/package_tarball64/build/src/gf.c:1942
jl_apply at /home/centos/buildbot/slave/package_tarball64/build/src/julia.h:1392 [inlined]
jl_f__apply at /home/centos/buildbot/slave/package_tarball64/build/src/builtins.c:547
_pycall at /root/.julia/v0.5/PyCall/src/PyCall.jl:534
jl_call_method_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:189 [inlined]
jl_apply_generic at /home/centos/buildbot/slave/package_tarball64/build/src/gf.c:1942
jl_apply at /home/centos/buildbot/slave/package_tarball64/build/src/julia.h:1392 [inlined]
jl_f__apply at /home/centos/buildbot/slave/package_tarball64/build/src/builtins.c:547
#pycall#69 at /root/.julia/v0.5/PyCall/src/PyCall.jl:565
show at /root/.julia/v0.5/PyCall/src/exception.jl:39
unknown function (ip: 0x7f3c2e912916)
jl_call_method_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:189 [inlined]
jl_apply_generic at /home/centos/buildbot/slave/package_tarball64/build/src/gf.c:1942
show_default at ./show.jl:130
unknown function (ip: 0x7f3c2e9112b6)
jl_call_method_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:189 [inlined]
jl_apply_generic at /home/centos/buildbot/slave/package_tarball64/build/src/gf.c:1942
show at ./show.jl:116
unknown function (ip: 0x7f3c2e910d16)
jl_call_method_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:189 [inlined]
jl_apply_generic at /home/centos/buildbot/slave/package_tarball64/build/src/gf.c:1942
jl_apply at /home/centos/buildbot/slave/package_tarball64/build/src/julia.h:1392 [inlined]
jl_show at /home/centos/buildbot/slave/package_tarball64/build/src/builtins.c:972
ffi_call_unix64 at /usr/lib/x86_64-linux-gnu/libffi.so.6 (unknown line)
ffi_call at /usr/lib/x86_64-linux-gnu/libffi.so.6 (unknown line)
```
