### ISSUE TITLE
OS X: OSError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaPy/pyjulia#80]
```
[Macintosh-3:~] solver% /Users/solver/.julia/v0.5/Conda/deps/usr/bin/python
Python 2.7.12 |Continuum Analytics, Inc.| (default, Jul  2 2016, 17:43:17) 
[GCC 4.2.1 (Based on Apple Inc. build 5658) (LLVM build 2336.11.00)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import julia
>>> j = julia.Julia()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/solver/.julia/v0.5/Conda/deps/usr/lib/python2.7/site-packages/julia-0.1.1-py2.7.egg/julia/core.py", line 271, in __init__
    """])
  File "/Users/solver/.julia/v0.5/Conda/deps/usr/lib/python2.7/subprocess.py", line 567, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/Users/solver/.julia/v0.5/Conda/deps/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/Users/solver/.julia/v0.5/Conda/deps/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by dlfivefifty** [comment]
The problem is JULIA_HOME needs to be defined.  The docs should be updated.

**Comment by dlfivefifty** [comment]
Nevermind, that didn't fix the issue..

**Comment by dlfivefifty** [comment]
I made a pull request to update the docs: https://github.com/JuliaPy/pyjulia/pull/81
