### ISSUE TITLE
ERROR: system image file "/usr/lib/x86_64-linux-gnu/julia/sys.so" not found

### ISSUE THREAD

**Issue by ldemattos** [JuliaPy/pyjulia#88]
I'm trying to rewrite some of my slow python modules with julia to gain some speed up.

I had installed julia (0.4.5) in Ubuntu 16.04.02 with apt-get.

Then in julia terminal I installed pycall:

> Pkg.add("PyCall")

After that, installed pyjulia with: 
pip install https://github.com/JuliaPy/pyjulia/archive/master.zip --user

When I attempt to instantiate julia object in python terminal, doing:
> import julia
> j = julia.Julia()

I'm getting:

> ERROR: system image file "/usr/lib/x86_64-linux-gnu/julia/sys.so" not found

Any tips to solve this issue?

**Comment by ldemattos** [comment]
Just to inform, I do have the not found file.

>$ file /usr/lib/x86_64-linux-gnu/julia/sys.so
>/usr/lib/x86_64-linux-gnu/julia/sys.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=df5e64a7fb100a1d5c5fd678c0213d8ac450f744, stripped```

**Comment by tkelman** [comment]
Try with a version of Julia from the generic Linux binaries. pyjulia may be assuming some default relative paths that aren't the case with the apt-get packaged version of Julia (which is out of date and we generally don't recommend using it).

**Comment by ldemattos** [comment]
@tkelman , thanks for the response. I will try the newer julia version as you suggested.

**Comment by ldemattos** [comment]
With the newer julia version (0.5.1) linux binary compiled I was able to successful instatiate an pyjulia object. However I had to adjust jl_runtime_path and jl_init_path. Here is the python script: https://gist.github.com/ldemattos/ad283e47e27e820cd37296aaa2beaa15

**Comment by ldemattos** [comment]
I'll close this issue since I was able to use pyjulia with another Julia version, however I'm not quite sure if it is actually solved.

@tkelman , thank you very much for the version advice.

**Comment by sirgogo** [comment]
I had this same error using 0.5.2 on Ubuntu. So, I tried updating to the Ubuntu nightly, 0.6.0, but then I get a different error. Any ideas?

Log:
`$ python                                                                                               
Python 3.5.2 |Intel Corporation| (default, Aug 15 2016, 04:18:36)                                                                   
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)] on linux                                                                                    
Type "help", "copyright", "credits" or "license" for more information.                                                              
Intel(R) Distribution for Python is brought to you by Intel Corporation.                                                            
Please check out: https://software.intel.com/en-us/python-distribution                                                              
>>> import julia                                                                                                                    
>>> j = julia.Julia()                                                                                                               
Error processing line 1 of /opt/intel/intelpython35/lib/python3.5/site-packages/protobuf-3.2.0-py3.5-nspkg.pth:                     
                                                                                                                                    
Failed to import the site module                                                                                                    
Traceback (most recent call last):                                                                                                  
  File "/opt/intel/intelpython35/lib/python3.5/site.py", line 167, in addpackage                                                    
    exec(line)                                                                                                                      
  File "<string>", line 1, in <module>                                                                                              
  File "/opt/intel/intelpython35/lib/python3.5/types.py", line 166, in <module>                                                     
    import functools as _functools                                                                                                  
  File "/opt/intel/intelpython35/lib/python3.5/functools.py", line 21, in <module>                                                  
    from collections import namedtuple                                                                                              
  File "/opt/intel/intelpython35/lib/python3.5/collections/__init__.py", line 29, in <module>                                       
    import heapq as _heapq                                                                                                          
  File "/opt/intel/intelpython35/lib/python3.5/heapq.py", line 587, in <module>                                                     
    from _heapq import *                                                                                                            
SystemError: initialization of _heapq did not return an extension module                                                            
                                                                                                                                    
During handling of the above exception, another exception occurred:                                                                 
                                                                                                                                    
Traceback (most recent call last):                                                                                                  
  File "/opt/intel/intelpython35/lib/python3.5/site.py", line 582, in <module>                                                      
    main()                                                                                                                          
  File "/opt/intel/intelpython35/lib/python3.5/site.py", line 568, in main                                                          
    known_paths = addsitepackages(known_paths)                                                                                      
  File "/opt/intel/intelpython35/lib/python3.5/site.py", line 327, in addsitepackages                                               
    addsitedir(sitedir, known_paths)                                                                                                
  File "/opt/intel/intelpython35/lib/python3.5/site.py", line 206, in addsitedir                                                    
    addpackage(sitedir, name, known_paths)                                                                                          
  File "/opt/intel/intelpython35/lib/python3.5/site.py", line 177, in addpackage                                                    
    import traceback                                                                                                                
  File "/opt/intel/intelpython35/lib/python3.5/traceback.py", line 3, in <module>                                                   
    import collections                                                                                                              
  File "/opt/intel/intelpython35/lib/python3.5/collections/__init__.py", line 29, in <module>                                       
    import heapq as _heapq                                                                                                          
  File "/opt/intel/intelpython35/lib/python3.5/heapq.py", line 587, in <module>                                                     
    from _heapq import *                                                                                                            
SystemError: initialization of _heapq did not return an extension module `

**Comment by tkelman** [comment]
use the generic linux binaries, not the ppa

**Comment by ldemattos** [comment]
@sirgogo , you're trying to load pyjulia with Intel Python interpreter. Why don't try first with native Ubuntu Python intepreter and then you try with Intel's?
