### ISSUE TITLE
AttributeError on j = julia.Julia()

### ISSUE THREAD

**Issue by Waponiwoo** [JuliaPy/pyjulia#95]
I keep getting the error below on my win 7 box.  any ideas?
I tried reinstalling PyCall and pyjulia with no luck. 

julia> Pkg.installed("PyCall")
v"1.11.1"

thanks, 

import julia

j = julia.Julia()
Traceback (most recent call last):

  File "<ipython-input-2-f420be51b3fc>", line 1, in <module>
    j = julia.Julia()

  File "build\bdist.win-amd64\egg\julia\core.py", line 288, in __init__
    self.api.jl_bytestring_ptr.restype = char_p

  File "C:\Users\BFH3\AppData\Local\Continuum\Anaconda2\lib\ctypes\__init__.py", line 375, in __getattr__
    func = self.__getitem__(name)

  File "C:\Users\BFH3\AppData\Local\Continuum\Anaconda2\lib\ctypes\__init__.py", line 380, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))

AttributeError: function 'jl_bytestring_ptr' not found

**Comment by tkf** [comment]
I'm closing it since this issue is old.  Newer versions of PyJulia/Julia/Python may solve it.  Please reopen if you still have the issue.
